# This is the configuration file for the worldcat.py script. 
# Use this file to define the various parameters for running the script. 



# Path to the folder in which the top-level folder of 
# the intended ELTeC repository is found. (Not directly the folder
# that contains XML-TEI files.)

#xmlpath: "C:/Users/Johanna/worldcat/COST-ELTeC" # Example on Windows
xmlpath : "/media/christof/mydata/repos/cost/" # Example on Linux

# Language of the collection. Only those entries in WorldCat will be 
# considered that correspond to this language.

lang : "ita" # fra, eng

# choose level of xml-files:

level : "level1" # level0, level2

# Working directory

wdir : ""

# CSV file

csv_file : "metadata.csv"

# Folder for the HTML files

write_file : "html"

htmlpages : "html/*.html"

# Suchstring plain
plain_suchstring : "https://www.worldcat.org/search?q=ti%3A{}+au%3A{}&fq=+%28x0%3Abook-+OR+%28x0%3Abook+x4%3Aprintbook%29+-%28%28x0%3Abook+x4%3Adigital%29%29+-%28%28x0%3Abook+x4%3Amic%29%29+-%28%28x0%3Abook+x4%3Abraille%29%29+-%28%28x0%3Abook+x4%3Alargeprint%29%29%29+%3E+ln%3A{}+%3E+ln%3A{}&dblist=638&start={}&qt=page_number_link"
#plain_suchstring : "https://www.worldcat.org/search?q=ti%3A{}+au%3A{}&fq=+%28x0%3Abook-+OR+%28x0%3Abook+x4%3Aprintbook%29+OR+%28x0%3Abook+x4%3Alargeprint%29+-%28%28x0%3Abook+x4%3Adigital%29%29+-%28%28x0%3Abook+x4%3Amic%29%29+-%28%28x0%3Abook+x4%3Abraille%29%29%29+%3E+ln%3A{}&dblist=638&start={}&qt=page_number_link"
