# This is the configuration file for the worldcat.py script. 
# Use this file to define the various parameters for running the script. 



# Path to the folder containing the XML-TEI files for which WorldCat 
# statistics will be retrieved. 

#xmlpath : "/home/christof/repos/cost/worldcat/test_xml/*.xml" 

# Language of the collection. Only those entries in WorldCat will be 
# considered that correspond to this language.

lang : "fra"

# Working directory

wdir : ""

# CSV file

csv_file : "metadata.csv"

# Folder for the HTML files

write_file : "html"

htmlpages : "html/*.html"

# Suchstring plain

plain_suchstring : "https://www.worldcat.org/search?q=ti%3A{}+au%3A{}&fq=+%28%28x0%3Abook+x4%3Aprintbook%29%29+%3E+ln%3Afre+%3E+ln%3Afre&dblist=638&start={}&qt=page_number_link"
