# This is the configuration file for the worldcat.py script. 
# Use this file to define the various parameters for running the script. 



# Path to the folder in which the top-level folder of 
# the intended ELTeC repository is found. (Not directly the folder
# that contains XML-TEI files.)

#basedir: "C:/Users/Johanna/Desktop/ELTeC_worldcat/ELTeC" # Example on Windows
basedir : "/media/christof/mydata/repos/cost/" # Example on Linux


# Language of the collection. Only those entries in WorldCat will be 
# considered that correspond to this language.

lang : "slv" # fra, eng, deu, ita, por, spa, srp, gre, hun, slv, rom, nor, cze, lit

# Choose level of xml-files:

level : "level1" # level0, level2

# Working directory
# Path where Scripts are stored and where are subfolder for the neccessary html-pages will be stored

wdir : ""

# Results
# Path to the folder where results (csv-files) are stored
# if no changes are made, it will be the working directory path

results : "" 
